@echo off
echo Starting Iris v3 Telemedicine System...

echo Freeing up Port 3000 to prevent conflicts...
call npx -y kill-port 3000 > NUL 2>&1

echo Starting Next.js Frontend...
start "Iris Next.js" cmd /c "npm run dev"

echo Starting Python STT Agent...
start "Iris Python Agent" cmd /k "cd worker && call .\venv\Scripts\activate.bat && python agent.py dev"

echo Waiting for Next.js to initialize...
ping 127.0.0.1 -n 6 > nul

echo Opening Patient Portal...
start http://localhost:3000

echo Opening Doctor Portal...
start http://localhost:3000/doctor

echo All services started successfully!
